<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-26 19:42
=======
# Generated by Django 5.2.6 on 2025-09-25 19:29
>>>>>>> origin/django-admin

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("rg", models.CharField(max_length=20, unique=True)),
                ("crm", models.CharField(max_length=20, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "especialidades",
                    models.ManyToManyField(
                        related_name="medicos", to="medicos.especialidade"
                    ),
                ),
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=20, unique=True)),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('especialidades', models.ManyToManyField(related_name='medicos', to='medicos.especialidade')),
>>>>>>> origin/django-admin
            ],
        ),
    ]
