# Generated by Django 5.2.4 on 2025-10-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(unique=True)),
                ('rg', models.CharField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField()),
                ('data_nasc', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
    ]
