<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-26 19:42
=======
# Generated by Django 5.2.6 on 2025-09-25 19:29
>>>>>>> origin/django-admin

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cpf", models.CharField(unique=True)),
                ("rg", models.CharField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField()),
                ("data_nasc", models.DateField()),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                    ),
                ),
                ("endereco", models.CharField(max_length=255)),
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(unique=True)),
                ('rg', models.CharField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField()),
                ('data_nasc', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('endereco', models.CharField(max_length=255)),
>>>>>>> origin/django-admin
            ],
        ),
    ]
