# Generated by Django 5.2.4 on 2025-11-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=100),
            preserve_default=False,
        ),
    ]
