# Generated by Django 5.2.7 on 2025-11-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='endereco',
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='pacientes.paciente')),
            ],
        ),
    ]
