# Generated by Django 5.2.5 on 2025-10-21 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_remove_paciente_email_remove_paciente_nome_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paciente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
