# Generated by Django 5.2.7 on 2025-12-01 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('sala', models.CharField(choices=[('SALA_GERAL_1', 'Sala de Atendimento Geral 1'), ('SALA_GERAL_2', 'Sala de Atendimento Geral 2'), ('SALA_CIRURGIA_PRIN', 'Sala de Cirurgia Principal'), ('SALA_PROFILAXIA', 'Sala de Profilaxia e Higiene'), ('SALA_ORTODONTIA', 'Sala de Ortodontia'), ('SALA_PEDIATRICA', 'Sala Pediátrica'), ('SALA_ENDODONTIA', 'Sala de Endodontia'), ('SALA_ESTETICA', 'Sala de Estética e Clareamento'), ('SALA_RADIOLOGIA', 'Sala de Radiologia e Imagem'), ('SALA_EMERGENCIA', 'Sala de Emergência Rápida')], max_length=50)),
                ('servico', models.CharField(choices=[('AVALIACAO', 'Avaliação e Diagnóstico'), ('PROFILAXIA', 'Profilaxia e Higiene'), ('RESTAU', 'Restauração Dentária'), ('CLAREAMENTO', 'Clareamento Dental'), ('ESTETICA_GERAL', 'Procedimento de Odontologia Estética Geral'), ('PROTESE', 'Reabilitação Protética'), ('IMPLANTE', 'Implante Dentário'), ('CANAL', 'Tratamento Endodôntico'), ('PERIODONTAL', 'Tratamento Periodontal'), ('ORTODONTIA', 'Instalação/Manutenção Ortodôntica'), ('EXTRACAO', 'Extração Dentária Simples'), ('CIRURGIA_MAXILO', 'Cirurgia Bucomaxilofacial Complexa'), ('ODONTOPED', 'Consulta/Tratamento Infantil'), ('RADIOLOGIA', 'Exames de Imagem Odontológica'), ('ESTOMATO', 'Avaliação de Lesões Orais')], max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('marcada', 'Marcada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('remarcada', 'Remarcada')], max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='medicos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doencas_cronicas', models.TextField()),
                ('medicamentos', models.TextField()),
                ('queixa_principal', models.TextField()),
                ('historico', models.TextField()),
                ('alergia', models.TextField()),
                ('observacao', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='consultas.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CÁRIE DENTÁRIA', 'Cárie dentária'), ('PULPITE', 'Pulpite'), ('ABSCESSO DENTÁRIO', 'Abscesso dentário'), ('PERIODONTITE', 'Periodontite'), ('GENGIVITE', 'Gengivite'), ('HIPERSENSIBILIDADE DENTINÁRIA', 'Hipersensibilidade dentinária'), ('MÁ OCLUSÃO', 'Má oclusão'), ('APINHAMENTO DENTÁRIO', 'Apinhamento dentário'), ('MORDIDA CRUZADA', 'Mordida cruzada'), ('SOBREMORDIDA', 'Sobremordida'), ('MORDIDA ABERTA', 'Mordida aberta'), ('DISFUNÇÃO TEMPOROMANDIBULAR', 'Disfunção temporomandibular (DTM)'), ('BRUXISMO', 'Bruxismo'), ('PERDA ÓSSEA', 'Perda óssea alveolar'), ('ULCERAÇÃO ORAL', 'Ulceração oral'), ('CANDIDÍASE ORAL', 'Candidíase oral'), ('LEUCOPLASIA', 'Leucoplasia'), ('LÍQUEN PLANO ORAL', 'Líquen plano oral'), ('ALTERAÇÃO ESTÉTICA', 'Alteração estética'), ('FRATURA DENTÁRIA', 'Fratura dentária'), ('RETENÇÃO DE DENTE DECÍDUO', 'Retenção de dente decíduo'), ('DENTE INCLUSO', 'Dente incluso'), ('OUTRO', 'Outro')], max_length=100)),
                ('plano_de_tratamento', models.TextField()),
                ('detalhes', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='consultas.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[], max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('consultas', models.ManyToManyField(related_name='exames', to='consultas.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadeMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('sala_padrao', models.CharField(choices=[('SALA_GERAL_1', 'Sala de Atendimento Geral 1'), ('SALA_GERAL_2', 'Sala de Atendimento Geral 2'), ('SALA_CIRURGIA_PRIN', 'Sala de Cirurgia Principal'), ('SALA_PROFILAXIA', 'Sala de Profilaxia e Higiene'), ('SALA_ORTODONTIA', 'Sala de Ortodontia'), ('SALA_PEDIATRICA', 'Sala Pediátrica'), ('SALA_ENDODONTIA', 'Sala de Endodontia'), ('SALA_ESTETICA', 'Sala de Estética e Clareamento'), ('SALA_RADIOLOGIA', 'Sala de Radiologia e Imagem'), ('SALA_EMERGENCIA', 'Sala de Emergência Rápida')], max_length=50)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidade', to='medicos.medico')),
            ],
            options={
                'verbose_name': 'Disponibilidade do Médico',
                'verbose_name_plural': 'Disponibilidades dos Médicos',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('medico', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
