# Generated by Django 5.2.6 on 2025-10-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('sala', models.CharField(max_length=50)),
                ('servico', models.CharField(choices=[('AVALIACAO', 'Avaliação'), ('LIMPEZA', 'Limpeza'), ('RESTAU', 'Restauração'), ('CANAL', 'Tratamento de canal'), ('EXTRACAO', 'Extração dentária'), ('CLAREAMENTO', 'Clareamento'), ('APARELHO', 'Ortodontia')], max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('marcada', 'Marcada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('remarcada', 'Remarcada')], max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='medicos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doencas_cronicas', models.TextField()),
                ('medicamentos', models.TextField()),
                ('queixa_principal', models.TextField()),
                ('historico', models.TextField()),
                ('alergia', models.TextField()),
                ('observacao', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='pacientes.paciente')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='consultas.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[], max_length=100)),
                ('plano_de_tratamento', models.TextField()),
                ('detalhes', models.TextField()),
                ('consulta', models.ManyToManyField(related_name='diagnosticos', to='consultas.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[], max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('consultas', models.ManyToManyField(related_name='exames', to='consultas.consulta')),
            ],
        ),
    ]
