# Generated by Django 5.2.6 on 2025-09-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='servico',
            field=models.CharField(choices=[('AVALIACAO', 'Avaliação'), ('LIMPEZA', 'Limpeza'), ('RESTAU', 'Restauração'), ('CANAL', 'Tratamento de canal'), ('EXTRACAO', 'Extração dentária'), ('CLAREAMENTO', 'Clareamento'), ('APARELHO', 'Ortodontia')], max_length=100),
        ),
    ]
