# Generated by Django 5.2.5 on 2025-11-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostico",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CÁRIE DENTÁRIA", "Cárie dentária"),
                    ("PULPITE", "Pulpite"),
                    ("ABSCESSO DENTÁRIO", "Abscesso dentário"),
                    ("PERIODONTITE", "Periodontite"),
                    ("GENGIVITE", "Gengivite"),
                    ("HIPERSENSIBILIDADE DENTINÁRIA", "Hipersensibilidade dentinária"),
                    ("MÁ OCLUSÃO", "Má oclusão"),
                    ("APINHAMENTO DENTÁRIO", "Apinhamento dentário"),
                    ("MORDIDA CRUZADA", "Mordida cruzada"),
                    ("SOBREMORDIDA", "Sobremordida"),
                    ("MORDIDA ABERTA", "Mordida aberta"),
                    (
                        "DISFUNÇÃO TEMPOROMANDIBULAR",
                        "Disfunção temporomandibular (DTM)",
                    ),
                    ("BRUXISMO", "Bruxismo"),
                    ("PERDA ÓSSEA", "Perda óssea alveolar"),
                    ("ULCERAÇÃO ORAL", "Ulceração oral"),
                    ("CANDIDÍASE ORAL", "Candidíase oral"),
                    ("LEUCOPLASIA", "Leucoplasia"),
                    ("LÍQUEN PLANO ORAL", "Líquen plano oral"),
                    ("ALTERAÇÃO ESTÉTICA", "Alteração estética"),
                    ("FRATURA DENTÁRIA", "Fratura dentária"),
                    ("RETENÇÃO DE DENTE DECÍDUO", "Retenção de dente decíduo"),
                    ("DENTE INCLUSO", "Dente incluso"),
                    ("OUTRO", "Outro"),
                ],
                max_length=100,
            ),
        ),
    ]
