# Generated by Django 5.2.7 on 2025-11-14 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_diagnostico_tipo'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='sala',
            field=models.CharField(choices=[('SALA_GERAL_1', 'Sala de Atendimento Geral 1 (Rotina)'), ('SALA_GERAL_2', 'Sala de Atendimento Geral 2 (Rotina)'), ('SALA_CIRURGIA_PRIN', 'Sala de Cirurgia Principal'), ('SALA_PROFILAXIA', 'Sala de Profilaxia e Higiene'), ('SALA_ORTODONTIA', 'Sala de Ortodontia'), ('SALA_PEDIATRICA', 'Sala Pediátrica'), ('SALA_ENDODONTIA', 'Sala de Endodontia (Tratamento de Canal)'), ('SALA_ESTETICA', 'Sala de Estética e Clareamento'), ('SALA_RADIOLOGIA', 'Sala de Radiologia e Imagem'), ('SALA_EMERGENCIA', 'Sala de Emergência Rápida')], max_length=50),
        ),
        migrations.CreateModel(
            name='DisponibilidadeMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('sala_padrao', models.CharField(choices=[('SALA_GERAL_1', 'Sala de Atendimento Geral 1 (Rotina)'), ('SALA_GERAL_2', 'Sala de Atendimento Geral 2 (Rotina)'), ('SALA_CIRURGIA_PRIN', 'Sala de Cirurgia Principal'), ('SALA_PROFILAXIA', 'Sala de Profilaxia e Higiene'), ('SALA_ORTODONTIA', 'Sala de Ortodontia'), ('SALA_PEDIATRICA', 'Sala Pediátrica'), ('SALA_ENDODONTIA', 'Sala de Endodontia (Tratamento de Canal)'), ('SALA_ESTETICA', 'Sala de Estética e Clareamento'), ('SALA_RADIOLOGIA', 'Sala de Radiologia e Imagem'), ('SALA_EMERGENCIA', 'Sala de Emergência Rápida')], max_length=50)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidade', to='medicos.medico')),
            ],
            options={
                'verbose_name': 'Disponibilidade do Médico',
                'verbose_name_plural': 'Disponibilidades dos Médicos',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('medico', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
