# Generated by Django 5.2.7 on 2025-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_sala_disponibilidademedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='sala',
            field=models.CharField(choices=[('SALA_GERAL_1', 'Sala de Atendimento Geral 1'), ('SALA_GERAL_2', 'Sala de Atendimento Geral 2'), ('SALA_CIRURGIA_PRIN', 'Sala de Cirurgia Principal'), ('SALA_PROFILAXIA', 'Sala de Profilaxia e Higiene'), ('SALA_ORTODONTIA', 'Sala de Ortodontia'), ('SALA_PEDIATRICA', 'Sala Pediátrica'), ('SALA_ENDODONTIA', 'Sala de Endodontia'), ('SALA_ESTETICA', 'Sala de Estética e Clareamento'), ('SALA_RADIOLOGIA', 'Sala de Radiologia e Imagem'), ('SALA_EMERGENCIA', 'Sala de Emergência Rápida')], max_length=50),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='servico',
            field=models.CharField(choices=[('AVALIACAO', 'Avaliação e Diagnóstico'), ('PROFILAXIA', 'Profilaxia e Higiene'), ('RESTAU', 'Restauração Dentária'), ('CLAREAMENTO', 'Clareamento Dental'), ('ESTETICA_GERAL', 'Procedimento de Odontologia Estética Geral'), ('PROTESE', 'Reabilitação Protética'), ('IMPLANTE', 'Implante Dentário'), ('CANAL', 'Tratamento Endodôntico'), ('PERIODONTAL', 'Tratamento Periodontal'), ('ORTODONTIA', 'Instalação/Manutenção Ortodôntica'), ('EXTRACAO', 'Extração Dentária Simples'), ('CIRURGIA_MAXILO', 'Cirurgia Bucomaxilofacial Complexa'), ('ODONTOPED', 'Consulta/Tratamento Infantil'), ('RADIOLOGIA', 'Exames de Imagem Odontológica'), ('ESTOMATO', 'Avaliação de Lesões Orais')], max_length=100),
        ),
        migrations.AlterField(
            model_name='disponibilidademedico',
            name='sala_padrao',
            field=models.CharField(choices=[('SALA_GERAL_1', 'Sala de Atendimento Geral 1'), ('SALA_GERAL_2', 'Sala de Atendimento Geral 2'), ('SALA_CIRURGIA_PRIN', 'Sala de Cirurgia Principal'), ('SALA_PROFILAXIA', 'Sala de Profilaxia e Higiene'), ('SALA_ORTODONTIA', 'Sala de Ortodontia'), ('SALA_PEDIATRICA', 'Sala Pediátrica'), ('SALA_ENDODONTIA', 'Sala de Endodontia'), ('SALA_ESTETICA', 'Sala de Estética e Clareamento'), ('SALA_RADIOLOGIA', 'Sala de Radiologia e Imagem'), ('SALA_EMERGENCIA', 'Sala de Emergência Rápida')], max_length=50),
        ),
    ]
